SELECT
     B.DTFAT
    ,B.DATA
    ,A.CODCLI
    ,A.NUMPED 
    ,A.CODPROD
    ,A.PUNIT
    ,A.PTABELA
    ,A.QT
    ,A.CODUSUR
    ,ROUND(NVL(SUM(A.QT * A.PTABELA),0) + NVL(SUM(A.QT * A.VLFRETE),0) + NVL(SUM(B.VLOUTRASDESP),0),2) AS "TOTAL TABELA"
    ,ROUND(NVL(SUM(A.QT * A.PUNIT),0) + NVL(SUM(A.QT * A.VLFRETE),0) + NVL(SUM(B.VLOUTRASDESP),0),2) AS "TOTAL VENDA"
    ,ROUND((A.PERCDESC / 100),2) AS PERCENTUAL_DESCONTO
FROM
    PCMOV A
        LEFT JOIN PCPEDC B ON A.NUMPED = B.NUMPED
        INNER JOIN PCPRODUT C ON C.CODPROD = A.CODPROD

WHERE
    B.POSICAO  IN ('F')
    AND A.CODOPER = 'S'
    AND B.DTCANCEL IS NULL
    AND EXTRACT(YEAR FROM B.DATA) >= EXTRACT(YEAR FROM SYSDATE) -0
    AND B.CONDVENDA NOT IN (4, 8, 10)
    AND B.CODFILIAL IN (1, 10 , 11 , 12,  13, 14 ,16 ,2,3,4,7,8,9) 
    and B.DTFAT in ('18/10/2022','19/10/2022','20/10/2022')
    and A.PUNIT=19
    and A.CODPROD=1430

GROUP BY
    B.DTFAT, A.CODCLI, B.DATA, A.NUMPED, A.PUNIT, 
    A.CODPROD, A.PTABELA, A.CODUSUR, A.QT,  
    A.PERCDESC / 100, 100, 100, A.CODPROD||'-'||C.DESCRICAO, '-', 
    C.DESCRICAO, '-', C.DESCRICAO

ORDER BY DTFAT DESC