SELECT
    B.DTFAT,
    B.data dt,
    bi.CODCLI AS CODCLI,
    UPPER( LPAD( A.CODCLI, 6, '0')||' - '||G.CLIENTE) AS COD_CLIENTE,
    A.CODPROD AS CODPROD,
    LPAD( A.CODPROD, 6, '0')||' - '||C.DESCRICAO AS COD_PRODUTO,
    H.DESCRICAO AS DEPTO,
    LPAD( A.CODUSUR, 4, '0')||' - '||REGEXP_SUBSTR(D.NOME,'(\w+)',1,1) AS COD_RCA,
    B.CODSUPERVISOR,
    REGEXP_SUBSTR( E.NOME,'(\w+)',1,1) ||' '|| REGEXP_SUBSTR(E.NOME,'(\w+)',1,2) AS SUPERVISOR,       
    DECODE( B.CODSUPERVISOR, '105', 'EQUIPE A', '82', 'EQUIPE B', '104', 'EQUIPE C', '96', 'EQUIPE D', '22', 'EQUIPE E', '100', 'INTERIOR', '103', 'REVENDA', '106', 'EXPANSÃO', '107', 'EXTERNA',  '108', 'EQUIPE H','109', 'ANALISTAS', '27', 'SITE') AS EQUIPE, 
    A.NUMPED AS PEDIDO,
    A.QT AS QTDE_VENDIDA,
    A.PUNIT AS PREÇO_VENDA,
    A.PTABELA AS PREÇO_TABELA,
    NVL(SUM(A.QT * A.PUNIT),0) + NVL(SUM(A.QT * A.VLFRETE),0) AS "TOTAL VENDA"
FROM
    PCPEDC B
        left Join pcpedi bi on b.numped=bi.numped 
        LEFT JOIN PCPRODUT C ON bi.CODPROD = C.CODPROD        
        LEFT JOIN PCMOV A  ON b.NUMPED = a.NUMPED        
        LEFT JOIN PCUSUARI D ON D.CODUSUR = bi.CODUSUR
        LEFT JOIN PCSUPERV E ON E.CODSUPERVISOR = D.CODSUPERVISOR
        LEFT JOIN PCCOORDENADORVENDA F ON F.CODIGO = E.CODCOORDENADOR
        LEFT JOIN PCCLIENT G ON G.CODCLI = bi.CODCLI
        LEFT JOIN PCDEPTO H ON H.CODEPTO = C.CODEPTO
WHERE
   b.numped
      in(
SELECT
    b.NUMPED 
   FROM
    PCPEDC B
        left Join pcpedi bi on b.numped=bi.numped 
        LEFT JOIN PCPRODUT C ON bi.CODPROD = C.CODPROD        
        LEFT JOIN PCMOV A  ON b.NUMPED = a.NUMPED        
        LEFT JOIN PCUSUARI D ON D.CODUSUR = bi.CODUSUR
        LEFT JOIN PCSUPERV E ON E.CODSUPERVISOR = D.CODSUPERVISOR
        LEFT JOIN PCCOORDENADORVENDA F ON F.CODIGO = E.CODCOORDENADOR
        LEFT JOIN PCCLIENT G ON G.CODCLI = bi.CODCLI
        LEFT JOIN PCDEPTO H ON H.CODEPTO = C.CODEPTO
WHERE
   -- B.POSICAO  IN ('F', 'C') AND
  --  E.POSICAO = 'A' AND
 --   A.CODOPER = 'S' AND
  --  B.DTCANCEL IS NULL AND
    B.data >= '18/10/2022' AND
    bi.CODPROD IN (1430) AND  
    B.CONDVENDA NOT IN (4, 8, 10) AND
    bi.pvenda = 19 AND
    B.CODFILIAL IN (1, 10, 11, 12, 13, 14, 16, 2, 3, 4, 7, 8, 9)
GROUP BY
    B.DTFAT,
    B.data,
    A.CODCLI,
    UPPER( LPAD( A.CODCLI, 6, '0')||' - '||G.CLIENTE),
    A.CODPROD,
    LPAD( A.CODPROD, 6, '0')||' - '||C.DESCRICAO,
    H.DESCRICAO,
    LPAD( A.CODUSUR, 4, '0')||' - '||REGEXP_SUBSTR(D.NOME,'(\w+)',1,1),
    B.CODSUPERVISOR,
    REGEXP_SUBSTR( E.NOME,'(\w+)',1,1) ||' '|| REGEXP_SUBSTR(E.NOME,'(\w+)',1,2),       
    DECODE( B.CODSUPERVISOR, '105', 'EQUIPE A', '82', 'EQUIPE B', '104', 'EQUIPE C', '96', 'EQUIPE D', '22', 'EQUIPE E', '100', 'INTERIOR', '103', 'REVENDA', '106', 'EXPANSÃO', '107', 'EXTERNA',  '108', 'EQUIPE H','109', 'ANALISTAS', '27', 'SITE'), 
    E.NOME,
    F.NOME,
    A.NUMPED,
    A.QT,
    A.PUNIT,
    A.PTABELA)
GROUP BY
    B.DTFAT,
     B.data,
    A.CODCLI,
    UPPER( LPAD( A.CODCLI, 6, '0')||' - '||G.CLIENTE),
    A.CODPROD,
    LPAD( A.CODPROD, 6, '0')||' - '||C.DESCRICAO,
    H.DESCRICAO,
    LPAD( A.CODUSUR, 4, '0')||' - '||REGEXP_SUBSTR(D.NOME,'(\w+)',1,1),
    B.CODSUPERVISOR,
    REGEXP_SUBSTR( E.NOME,'(\w+)',1,1) ||' '|| REGEXP_SUBSTR(E.NOME,'(\w+)',1,2),       
    DECODE( B.CODSUPERVISOR, '105', 'EQUIPE A', '82', 'EQUIPE B', '104', 'EQUIPE C', '96', 'EQUIPE D', '22', 'EQUIPE E', '100', 'INTERIOR', '103', 'REVENDA', '106', 'EXPANSÃO', '107', 'EXTERNA',  '108', 'EQUIPE H','109', 'ANALISTAS', '27', 'SITE'), 
    E.NOME,
    F.NOME,
    A.NUMPED,
    A.QT,
    A.PUNIT,
    A.PTABELA
