select * from (
SELECT O.NUMORCA,
BI.NUMPED,
O.DATA AS DATA_ORC,
CASE O.POSICAO
WHEN 'F' THEN B.DATA
WHEN 'B' THEN NULL
WHEN 'L' THEN B.DATA
ELSE B.DATA END AS DT_LIB,
BI.DATA AS DT_PED,
B.DTWMS AS DT_ESTOQUE,
B.DTFAT AS DT_FAT,
B.DTENTREGA AS DT_PREV_ENT,
CASE WHEN B.NUMCAR = 999999 THEN NULL ELSE (SELECT MIN(PC.DTFECHA) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR  ) END AS DTAFINALENTREGA,
BI.QT,BI.PVENDA,BI.QT*BI.PVENDA AS VALOR_PORD,O.VLTOTAL VALOR_ORC,
BI.CODCLI,
B.VLTOTAL,
B.totpeso,
b.totvolume,
C.CODPROD,
c.descricao,
O.CODPRACA,
ES.PRACA,
ES.NUMREGIAO,
ES.ROTA,
CASE O.POSICAO
WHEN 'F' THEN 'FATURADO'
WHEN 'B' THEN 'BLOQUEADO'
WHEN 'L' THEN 'LIBERADO'
ELSE 'CANCELADO' END AS POSICAO_ORC,
CASE BI.POSICAO
WHEN 'F' THEN 'FATURADO'
WHEN 'B' THEN 'BLOQUEADO'
WHEN 'L' THEN 'LIBERADO'
ELSE 'CANCELADO' END AS POSICAO_PED,
B.NUMNOTA,
B.NUMCAR,
(SELECT MIN(PC.DTFECHA) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR  )DTFECHA,
CASE 
WHEN (SELECT COUNT(*) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR AND PC.NUMNOTAS<>'0' AND PC.DTFECHA IS NOT NULL )>=1 THEN 'ENTREGUE' 
WHEN (SELECT COUNT(*) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR AND PC.NUMNOTAS<>'0' AND PC.DTFECHA IS NULL AND B.NUMCAR<>'999999'  )>=1 THEN 'ROTA' 
WHEN B.NUMCAR='999999'  THEN 'PATIO 99' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO='C' THEN 'PATIO FATURADO' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO='P' THEN 'PATIO FATURADO' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO='A' THEN 'PATIO FATURADO' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO IS NULL THEN 'PATIO FATURADO' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL AND PM.POSICAO='C' THEN 'SEPARACAO' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL AND PM.POSICAO='P' THEN 'SEPARACAO'
WHEN B.NUMCAR<>0 AND B.NUMCAR<>'999999' AND (SELECT COUNT(*) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR AND PC.DTFECHA IS NOT NULL )>0 THEN 'ENTREGUE'
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL  AND O.POSICAO='L' AND BI.POSICAO='L' AND PM.POSICAO IS NULL THEN 'LIBERADO' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL  AND O.POSICAO='L' AND BI.POSICAO='B' AND PM.POSICAO IS NULL THEN 'PEDIDO BLOQUEADO' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL  AND O.POSICAO='B'  AND PM.POSICAO IS NULL THEN 'ORÇAMENTO BLOQUEADO'
ELSE 'ORÇAMENTO BLOQUEADO' 
END AS ST,
CASE 
WHEN (SELECT COUNT(*) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR AND PC.NUMNOTAS<>'0' AND PC.DTFECHA IS NOT NULL )>=1 THEN '8' 
WHEN (SELECT COUNT(*) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR AND PC.NUMNOTAS<>'0' AND PC.DTFECHA IS NULL AND B.NUMCAR<>'999999'  )>=1 THEN '7' 
WHEN B.NUMCAR='999999'  THEN '6' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO='C' THEN '6' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO='P' THEN '6' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO='A' THEN '6' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NOT NULL AND PM.POSICAO IS NULL THEN '6' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL AND PM.POSICAO='C' THEN '5' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL AND PM.POSICAO='P' THEN '5'
WHEN B.NUMCAR<>0 AND B.NUMCAR<>'999999' AND (SELECT COUNT(*) FROM PCCARREG PC  WHERE  PC.NUMCAR=B.NUMCAR AND PC.DTFECHA IS NOT NULL )>0 THEN '8'
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL  AND O.POSICAO='L' AND BI.POSICAO='L' AND PM.POSICAO IS NULL THEN '4' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL  AND O.POSICAO='L' AND BI.POSICAO='B' AND PM.POSICAO IS NULL THEN '3' 
WHEN B.NUMCAR='0' AND B.DTFAT IS NULL  AND O.POSICAO='B'  AND PM.POSICAO IS NULL THEN '2'
ELSE '1' 
END AS ST2,
B.codusur,
c.longitude,
c.latitude
FROM PCORCAVENDAC O
LEFT JOIN PCPRACA ES ON O.CODPRACA=ES.CODPRACA
LEFT JOIN PCPEDC B ON O.NUMORCA=B.NUMPED
LEFT JOIN PCPEDI BI ON B.NUMPED=BI.NUMPED
LEFT JOIN PCPRODUT C ON C.CODPROD = BI.CODPROD
LEFT JOIN PCMOVENDPEND PM ON B.NUMPED=PM.NUMPED AND BI.CODPROD=pm.codprod
left join pcclient c on o.codcli=c.codcli
--lEFT JOIN PCPREST D ON  D.NUMCAR=B.NUMCAR
--LEFT JOIN PCCARREG G ON B.NUMCAR=G.NUMCAR  and d.duplic=B.NUMNOTA
WHERE
B.CONDVENDA NOT IN (4, 8, 7,10) AND
B.CODFILIAL IN (1,4,9)  and
BI.POSICAO <> 'C' and
o.data>=SYSDATE-60
)ped
 